### ISSUE TITLE
How to set exploration boundary in rviz

### ISSUE THREAD

**Issue by luo-pan** [hasauino/rrt_exploration_tutorials#1]
First, thank you for your sharing! When I define the rectangular region for exploration,  the "Publish Point" tool in the rviz to define the points isn't used normally.  In other words, the polygon for exploration is not defined normally.The package has been debugged on ROS Indigo. In short, can you point me to instructions on how to set the frontier exploration boundary in rviz? Thank you!

**Comment by hasauino** [comment]
Did you follow this tutorial:
http://wiki.ros.org/rrt_exploration/Tutorials/singleRobot

There you will find a gif image showing the correct sequence for publishing the five points

**Comment by luo-pan** [comment]
Yes, I did it according to the tutorial. But when I click the "Publish Point" tool rapidly, only one point  displays in the rviz.So I don't know the reason. The following vedio can illustrate the problem I have.
[ 2017-10-20 18:55:55.mp4.tar.gz](https://github.com/hasauino/rrt_exploration_tutorials/files/1401678/2017-10-20.18.55.55.mp4.tar.gz)

**Comment by luo-pan** [comment]
Yes, I did it according to the tutorial. But when I click the "Publish Point" tool repeatedly, only one point displays in the rviz.So I don't know the reason. The following vedio can illustrate the problem I have.
[屏幕录像 2017-10-20 18:55:55.mp4.zip](https://github.com/hasauino/rrt_exploration_tutorials/files/1401696/2017-10-20.18.55.55.mp4.zip)

**Comment by hasauino** [comment]
looks like both the local_rrt_detector and global_rrt_detector are not running. Becuase these nodes subcribe for the points published by Rviz. Did you run the"single.launch" file without any errors or something?

**Comment by luo-pan** [comment]
Yes, I did it according to the tutorial. But when I click the "Publish Point"  tool repeatedly, only one point displays in the rviz.So I don't know the reason. The following video can illustrate the problem I have. 
[ 2017-10-20 18:55:55.mp4.zip](https://github.com/hasauino/rrt_exploration_tutorials/files/1401708/2017-10-20.18.55.55.mp4.zip)

**Comment by hasauino** [comment]
Running this line: roslaunch rrt_exploration_tutorials single_simulated_house.launch
runs the simulation. From the video, this part you got it already.
This line:     roslaunch rrt_exploration single.launch

runs the global and local detectors, the filter, and the assigner nodes. If the detectors are not running, the points you click on Rviz won't be stored. So this is an indication the detector nodes (local_rrt_detector and global_rrt_detector ) are not running

**Comment by luo-pan** [comment]
I have tried it again and some errors and warns occured as is shown in the picture.
![2017-10-20 19 19 24](https://user-images.githubusercontent.com/32953076/31818770-1c2ead56-b5cc-11e7-9aca-1176604e151c.png)

**Comment by luo-pan** [comment]
THANK YOU! According to your advice , I made it !

**Comment by hasauino** [comment]
I can't tell from only this picture.
But try this; edit the "single.launch" file inside the "rrt_exploration" package, keeping only one node which the global detector. so will look like this:
```xml
<launch>
<arg name="eta" value="1.0"/>
<arg name="Geta" value="15.0"/>
  <node pkg="rrt_exploration" type="global_rrt_detector" name="global_detector" output="screen">
  <param name="eta" value="$(arg Geta)"/>
  <param name="map_topic" value="/robot_1/map"/>
  </node>
</launch>
```
And post me the error, yout tf tree, topics list and nodes list

**Comment by hasauino** [comment]
ops, ok good to hear that!

**Comment by luo-pan** [comment]
Mr hasauino, would you like to share your article here? To be honest,  I don't know the principle of your RRT algorithm in your article which I can't download. So I want to read your article and find more details which may help me implement the algorithm on a real robot. Looking forward to your reply. Thank you very much.

**Comment by hasauino** [comment]
I will add a link to the paper, it should be published in a month or so

**Comment by luo-pan** [comment]
Ok, Mr hasauino. Thanks for your sharing!

**Comment by hasauino** [comment]
You are welcome

**Comment by zwkcoding** [comment]
This exploration algorithm similar to this thesis: Receding Horizon "Next-Best-View" Planner for 3D Exploration(http://ieeexplore.ieee.org/document/7487281/) I read. Do you read this this paper? @hasauino

**Comment by zwkcoding** [comment]
Thanks for sharing! :+1: 
I'm looking forward to seeing your thesis to make a deep understanding!

**Comment by hasauino** [comment]
Thank you. Yes, I have read this paper, they also use RRT in their exploration. There are also another exploration algorithm which also uses a variation of RRT called SRT.
But the way we use RRT is different. We only use RRT to detect the exploration targets, once detected the robots do not follow the growing tree.
I will post a link for the published paper, once it gets indexed on IEEE (it may take a month or less).

**Comment by hasauino** [comment]
This is the [link ](http://ieeexplore.ieee.org/document/8202319/)for the paper describing the algorithm used in the package.

**Comment by zwkcoding** [comment]
:+1:
