### ISSUE TITLE
Unable to lunch launching single_simulated_house.launch

### ISSUE THREAD

**Issue by koshish** [hasauino/rrt_exploration_tutorials#10]
hercules@hercules:~/robot_operating_system/first_workspace/catkin_ws/src/rrt_exploration_tutorials/launch$ ls
includes                         mutliple_simulated_largeMap.launch  single_simulated_house.launch     single_simulated_MTR.launch
mutliple_simulated_house.launch  mutliple_simulated_MTR.launch       single_simulated_largeMap.launch

hercules@hercules:~/robot_operating_system/first_workspace/catkin_ws/src$ roslaunch rrt_exploration_tutorials single_simulated_house.launch
[single_simulated_house.launch] is neither a launch file in package [rrt_exploration_tutorials] nor is [rrt_exploration_tutorials] a launch file name
The traceback for the exception was written to the log file

**Comment by hasauino** [comment]
I think the problem might be your ROS package path not pointing to your catkin workspace correctly.

CHeck the ROS_PACKAGE_PATH environment variable (used by ROS to locate packages)
echo $ROS_PACKAGE_PATH






it should point out to two locations, one of them should be your catkin workspace.

**Comment by koshish** [comment]
@hasauino 

`h@hercules:~/robot_operating_system/first_workspace/catkin_ws$ echo $ROS_PACKAGE_PATH`
`/opt/ros/kinetic/share`

It shows only one path. What as I missing here?

**Comment by hasauino** [comment]
You can add your workspace to $ROS_PACKAGE_PATH environment variable by sourcing the setup file inside devel folder of your workspace:

source ~/robot_operating_system/first_workspace/catkin_ws/devel/setup.bash

you may also add this line to the bashrc file so this step happens automatically everytime you open a terminal:

**echo "source ~/robot_operating_system/first_workspace/catkin_ws/devel/setup.bash" >> ~/.bashrc**

**source ~/.bashrc**

**Comment by koshish** [comment]
@hasauino  Thank you.

Now it is working.
