### ISSUE TITLE
About simulation results

### ISSUE THREAD

**Issue by wangxiuzhong** [hasauino/rrt_exploration_tutorials#11]
Hi, 
I have read your paper about this package,it helps me very much.
But the results of  _the single robot simulation_ on my computer can not reach the experimental results in your paper.I want to know if the performance of the computer will affect the simulation results？
（e.g. I set the tree growth rate η =6,the TIME of a full exploration is approximately 140 seconds).
Thank you!

**Comment by hasauino** [comment]
I think computer specs do affect the results. However, I was using an old PC (though it had a dedicated graphics card).
As you see in the results figure, the readings have large standard deviation, so it's not odd to get a time of 140 sec.
I have checked my data though, the slowest exploration run on eta=6 in the large sim environment was 138 seconds. The fastest was 90 seconds.
Can you please send me a video of your explanation run. Also tell me what your pc specs are. You may also try to run the same exploration mission multiple times and see the results.

**Comment by wangxiuzhong** [comment]
Thanks for your reply,I have sent the video to your email，and the picture below is my computer specs:
![default](https://user-images.githubusercontent.com/30830961/40894886-0586cc96-679c-11e8-8803-6d8faabf1515.png)
Thank you again for your help!
