### ISSUE TITLE
How to create map in RViz for MOOR robot using rrt_exploration_tutorial launch files?

### ISSUE THREAD

**Issue by Sepideh-Bzh** [hasauino/rrt_exploration_tutorials#14]
Hi,
I have a problem about showing the map in Rviz when I add my robot(Moor) in your rrt_exploration_tutorial package as follows:
![image](https://user-images.githubusercontent.com/52884537/61187794-40d6e180-a68b-11e9-9e74-208244e65782.png)

The launch files and TF tree is constructed as follows:
![image](https://user-images.githubusercontent.com/52884537/61187861-3d902580-a68c-11e9-8160-2c64ad84de84.png)

I just changed the highlighted part and replaced my robot description
![image](https://user-images.githubusercontent.com/52884537/61187845-12a5d180-a68c-11e9-848c-581964cad46e.png)

![image](https://user-images.githubusercontent.com/52884537/61187715-133d6880-a68a-11e9-846b-9e3c8d393946.png)

what I can do to resolve this problem and create link between odom and base_link?

**Comment by hasauino** [comment]
Hi,
Your TF tree is not connected together, there is a missing transformation that should be published from ```robot_1/odom``` to ```robot_1/base_link```.

This is related to your ```mybot.xarco```. In my package I just use the Kobuki robot description file  which declares everything. The robot description file should not just be a URDF file defining the links and geometry of the robot, it should also include gazebo plugins for the robot (robot controller) and also for the sensors so the simulated robot can publish data same as a real robot. I'm not familiar with how this is done though.

**Comment by Sepideh-Bzh** [comment]
Thank you for your help
