### ISSUE TITLE
Any Advice on a good map merger for indigo ?

### ISSUE THREAD

**Issue by StanSmooth** [hasauino/rrt_exploration_tutorials#4]
Hi,
do you have a good advice on which map merger package should i choose for the multibot exploration ? 
the one you propose is only available on jade and sooner, and i didn't find any other package merging map without knowing initial position.

(thank you for your work !!)

**Comment by hasauino** [comment]
I was using the [map_merge ](https://github.com/hrnr/m-explore/tree/master/map_merge) package. I used it with known initial poses, and it was good.

That package was updated, and after the update, I had a problem with merging the maps. However, its older version which I  [forked ](https://github.com/hasauino/m-explore/tree/master/map_merge) still works fine.

**Comment by StanSmooth** [comment]
Thanks for your answer, I will definitly try this an I'll keep you in touch. 
isn't it available only for Jade and sooner ?

**Comment by hasauino** [comment]
I used it on ROS indigo and Kinect

**Comment by StanSmooth** [comment]
Working perfectly with your fork, thanks !

**Comment by hasauino** [comment]
You are welcome
