### ISSUE TITLE
Color Chart

### ISSUE THREAD

**Issue by StanSmooth** [hasauino/rrt_exploration_tutorials#5]
Hi hasauino, 
Could you give us some precisions about the color chart used on RViz ? 
From what i understood : 
-green dots corresponds to frontier point, delimiting area that the robot haven't explored yet
-red dot  : ? 
-blue line : pathe that the robot have already used
-red line : ? 
-green line : path that the robots will follow to join a frontier points

Once again, thank you for your work !

**Comment by hasauino** [comment]
Hello StanSmooth,
Color chart is as follows:

- Green points: All detected frontier points. The robot assigner allocates one of these points the robot.

- Red points: Last detected frontier point. (the global and local RRT detectors are continuously detecting frontier points).

- Red lines: Local RRT detector. These lines correspond to the tree edges of the local RRT.

- Blue lines: Global RRT detector, These lines correspond to the tree edges of the global RRT.

The navigation stack as you saw is also publishing markers on Rviz.  Colors are:
-Green path: is for the global planner.
-Blue path: is for the local planner.

**Comment by StanSmooth** [comment]
Thanks !

**Comment by hasauino** [comment]
you are welcome
