### ISSUE TITLE
merger_map position

### ISSUE THREAD

**Issue by chaowu644** [hasauino/rrt_exploration_tutorials#7]
Hi, hasauino
Thanks for share. I try to launch them, but in rviz the merger_map position is different from the other maps. It does not look like the video shows. How to fix it or change the map position in rviz?
Looking forward to your answer! Thank you for the working!

**Comment by hasauino** [comment]
You may try an older [fork](https://github.com/hasauino/m-explore) of the map merger node. This problem happened to me as well, but when I try the older version of the map merging package it works fine.

**Comment by chaowu644** [comment]
Thanks a lot! It works now.
