### ISSUE TITLE
rrt_exploration_tutorials seems not working with ros indigo and gazebo 7

### ISSUE THREAD

**Issue by StanSmooth** [hasauino/rrt_exploration_tutorials#8]

**Comment by hasauino** [comment]
Hello StanSmooth,
I have originally created those files on ROS indigo and with the default Gazebo version supported by indigo (which I think is gazebo 2).
So it should work..

**Comment by Alkhawaja** [comment]
Hello Hasan,

I was trying to run it on Gazebo 4.1 (I need it for the Gapter simulation), however it doesn't seem to be working.

Is there a way to install two gazebo versions at the same time in my Ubuntu 14.04 OS?

Thanks in advance...

**Comment by hasauino** [comment]
What error do you get? can you take a video of your screen when you run it?

Sorry I have no idea how to run two Gazebo versions on the same machine.

**Comment by Alkhawaja** [comment]
Hasan,

Apologies for the late reply.

Apparently, the error is this (copied from the terminal) : "Timed out waiting for transform from robot_1/base_link to robot_1/map to become available before running costmap, tf error: canTransform: target_frame robot_1/map does not exist.. canTransform returned after 2376.14 timeout was 0.1."

Regards,

Fares

**Comment by hasauino** [comment]
the gmapping node is responsible for publishing this transformation (robot_1/base_link to robot_1/map), check if the gmapping node is running ok, also the TF tree...

**Comment by Alkhawaja** [comment]
Yep, slam_gmapping (node) wasn't working. It is weird tho, the pkg was installed in both situations.
I will keep on figuring this out. Thanks a lot for your efforts.
