### ISSUE TITLE
About the mutliple simulated program

### ISSUE THREAD

**Issue by OoviceroO** [hasauino/rrt_exploration_tutorials#9]
Hi, hasauino .
I had lauch the mutliple_simulated_house.launch in your package . However , the result is different than the video which you have put in youtube. I don't know why the map counldn'd mrege well .  Could you help me think about it ?
Thank you for your work !
![2018-05-04 16-19-30](https://user-images.githubusercontent.com/33340115/39632851-d03cdcc6-4fe8-11e8-986f-7667215ffffc.png)

**Comment by hasauino** [comment]
This is related to the map merging node. In the video I was using an older version of the map merger which I forked here: https://github.com/hasauino/m-explore
Also, you need to make sure initial positions are set correctly, as explained in http://wiki.ros.org/multirobot_map_merge
